apiVersion: v1
kind: Service
metadata:
  name: model-serving
  namespace: agent
  labels:
    app: model-serving
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - name: ollama
      port: 11434
      targetPort: 11434
