apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: agent
  labels:
    app: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: agent/frontend-service:v15
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: backgrounds
              mountPath: /usr/share/nginx/html/backgrounds
              subPath: backgrounds
      volumes:
        - name: backgrounds
          persistentVolumeClaim:
            claimName: my-agent-assets-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: agent
  labels:
    app: frontend-service
spec:
  type: ClusterIP
  selector:
    app: frontend-service
  ports:
    - name: http
      port: 80
      targetPort: 80
