apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-backend-service
  namespace: agent
  labels:
    app: gateway-backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-backend-service
  template:
    metadata:
      labels:
        app: gateway-backend-service
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: gateway-backend-service
          image: agent/gateway-backend-service:v4
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 5210
          env:
            - name: SCHEDULER_CLIENT_MODE
              value: "grpc"
            - name: SCHEDULER_GRPC_TARGET
              value: "task-scheduler-service.agent.svc.cluster.local:5100"
            - name: SUBSCRIBER_ID
              value: "web-gateway-1"
            - name: USER_WHITELIST
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-backend-service
  namespace: agent
  labels:
    app: gateway-backend-service
spec:
  type: ClusterIP
  selector:
    app: gateway-backend-service
  ports:
    - name: http
      port: 5210
      targetPort: 5210
